name: Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:

  spec:
    name: Spec Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run spec tests
        run: bundle exec rake spec
